### ISSUE TITLE
Changes to sympy has caused breaking changes

### ISSUE THREAD

**Issue by muziker** [MarkCWirt/PyTuning#5]
Other than sympy.power.Pow -> sympy.core.power.Pow, sympy.numbers is now sympy.core.numbers. 

There's probably a couple of other changes in sympy.

**Comment by kennethreitz** [comment]
seconded

**Comment by MarkCWirt** [comment]
I'm, very sorry guys -- I haven't been on-line for a few years. I'll take care of this this weekend!

**Comment by MarkCWirt** [comment]
Hey guys, very very sorry for the delay.

I've fixed this and cleaned up the code a bit. The new package can be downloaded from here or at the Python package index:

```
pip install pytuning
# or
pip install pytuning==0.7.3
```

You probably aren't even interested in the software anymore. I don't blame you.

**Comment by MarkCWirt** [comment]
Fixed and on Pypi.
